# Generated by Django 4.2.7 on 2025-11-12 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_articlecategory_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='categories/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images', to='api.category')),
            ],
            options={
                'db_table': 'category_images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='articles/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='api.article')),
            ],
            options={
                'db_table': 'article_images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='products/%Y/%m/%d/')),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='api.fishproduct')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['-is_primary', 'display_order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'is_primary'], name='product_ima_product_c8c86a_idx'), models.Index(fields=['product', 'display_order'], name='product_ima_product_d1c257_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'is_primary'), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='categoryimage',
            index=models.Index(fields=['category'], name='category_im_categor_d9f38a_idx'),
        ),
        migrations.AddIndex(
            model_name='articleimage',
            index=models.Index(fields=['article'], name='article_ima_article_468bb7_idx'),
        ),
    ]
