# Generated by Django 4.2.7 on 2025-11-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_plants_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fishproduct',
            new_name='fish_produc_product_0c7102_idx',
            old_name='fish_product_type_idx',
        ),
        migrations.RenameIndex(
            model_name='plantcategory',
            new_name='plant_categ_slug_ee3375_idx',
            old_name='plant_categor_slug_idx',
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='plant_compatible_fauna',
            field=models.JSONField(blank=True, default=list, help_text='List of compatible fish species'),
        ),
        migrations.AddIndex(
            model_name='plantcategory',
            index=models.Index(fields=['is_active'], name='plant_categ_is_acti_6959ce_idx'),
        ),
    ]
