openapi: 3.0.3
info:
  title: Freshwater Fish Ecommerce - Orders API
  version: 1.0.0
  description: API contracts for order management and checkout

servers:
  - url: https://api.freshwater-fish-shop.com/v1
    description: Production server
  - url: http://localhost:8000/api/v1
    description: Development server

paths:
  /cart:
    get:
      summary: Get current user's cart
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cart contents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

    post:
      summary: Add item to cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - quantity
              properties:
                product_id:
                  type: string
                  format: uuid
                quantity:
                  type: integer
                  minimum: 1
      responses:
        '200':
          description: Item added to cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

    put:
      summary: Update cart item quantity
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - quantity
              properties:
                product_id:
                  type: string
                  format: uuid
                quantity:
                  type: integer
                  minimum: 0
      responses:
        '200':
          description: Cart updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

    delete:
      summary: Clear cart
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Cart cleared

  /cart/items/{product_id}:
    delete:
      summary: Remove item from cart
      security:
        - bearerAuth: []
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Item removed from cart

  /checkout:
    post:
      summary: Create order from cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutRequest'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetail'
        '400':
          description: Validation error (out of stock, invalid address, etc.)

  /orders:
    get:
      summary: List user's orders
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, confirmed, processing, shipped, delivered, cancelled]
      responses:
        '200':
          description: Orders list
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/OrderSummary'

  /orders/{id}:
    get:
      summary: Get order details
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetail'
        '404':
          description: Order not found

  /addresses:
    get:
      summary: List user's addresses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Addresses list
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Address'

    post:
      summary: Create new address
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressCreate'
      responses:
        '201':
          description: Address created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'

  /addresses/{id}:
    get:
      summary: Get address details
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Address details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'

    put:
      summary: Update address
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressUpdate'
      responses:
        '200':
          description: Address updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'

    delete:
      summary: Delete address
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Address deleted

components:
  schemas:
    Cart:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              product:
                $ref: '#/components/schemas/ProductSummary'
              quantity:
                type: integer
                minimum: 1
              unit_price:
                type: number
                format: decimal
              total_price:
                type: number
                format: decimal
        subtotal:
          type: number
          format: decimal
        shipping_estimate:
          type: number
          format: decimal
          nullable: true
        tax_estimate:
          type: number
          format: decimal
          nullable: true
        total:
          type: number
          format: decimal

    CheckoutRequest:
      type: object
      required:
        - shipping_address_id
      properties:
        shipping_address_id:
          type: string
          format: uuid
        billing_address_id:
          type: string
          format: uuid
        payment_method_id:
          type: string
          description: Payment method token from payment processor
        order_notes:
          type: string
          maxLength: 500

    OrderSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        order_number:
          type: string
        status:
          type: string
          enum: [pending, confirmed, processing, shipped, delivered, cancelled]
        total_amount:
          type: number
          format: decimal
        created_at:
          type: string
          format: date-time
        estimated_delivery:
          type: string
          format: date
          nullable: true

    OrderDetail:
      allOf:
        - $ref: '#/components/schemas/OrderSummary'
        - type: object
          properties:
            items:
              type: array
              items:
                type: object
                properties:
                  product:
                    $ref: '#/components/schemas/ProductSummary'
                  quantity:
                    type: integer
                  unit_price:
                    type: number
                    format: decimal
                  total_price:
                    type: number
                    format: decimal
            shipping_amount:
              type: number
              format: decimal
            tax_amount:
              type: number
              format: decimal
            discount_amount:
              type: number
              format: decimal
            payment_status:
              type: string
              enum: [pending, paid, failed, refunded]
            shipping_address:
              $ref: '#/components/schemas/Address'
            billing_address:
              $ref: '#/components/schemas/Address'
              nullable: true
            tracking_number:
              type: string
              nullable: true
            order_notes:
              type: string
              nullable: true
            updated_at:
              type: string
              format: date-time

    Address:
      type: object
      properties:
        id:
          type: string
          format: uuid
        address_type:
          type: string
          enum: [shipping, billing]
        first_name:
          type: string
        last_name:
          type: string
        company:
          type: string
          nullable: true
        address_line_1:
          type: string
        address_line_2:
          type: string
          nullable: true
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
        phone:
          type: string
          nullable: true
        is_default:
          type: boolean

    AddressCreate:
      type: object
      required:
        - address_type
        - first_name
        - last_name
        - address_line_1
        - city
        - state
        - postal_code
        - country
      properties:
        address_type:
          type: string
          enum: [shipping, billing]
        first_name:
          type: string
          maxLength: 30
        last_name:
          type: string
          maxLength: 30
        company:
          type: string
          maxLength: 50
        address_line_1:
          type: string
          maxLength: 100
        address_line_2:
          type: string
          maxLength: 100
        city:
          type: string
          maxLength: 50
        state:
          type: string
          maxLength: 50
        postal_code:
          type: string
          maxLength: 10
        country:
          type: string
          maxLength: 2
          default: US
        phone:
          type: string
          maxLength: 15
        is_default:
          type: boolean
          default: false

    AddressUpdate:
      allOf:
        - $ref: '#/components/schemas/AddressCreate'
        - type: object
          properties:
            address_type:
              type: string
              enum: [shipping, billing]
              description: Cannot be changed after creation

    ProductSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        species_name:
          type: string
        price:
          type: number
          format: decimal
        image_url:
          type: string
          format: uri
          nullable: true

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT