openapi: 3.0.3
info:
  title: Freshwater Fish Ecommerce - Articles API
  version: 1.0.0
  description: API contracts for article management system

servers:
  - url: https://api.freshwater-fish-shop.com/api/v1
    description: Production server
  - url: http://localhost:8000/api/v1
    description: Development server

paths:
  /articles:
    get:
      summary: List published articles with filtering and pagination
      tags:
        - Articles
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: category
          in: query
          schema:
            type: string
            format: uuid
            description: Filter by category ID
        - name: category_slug
          in: query
          schema:
            type: string
            description: Filter by category slug
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/ArticleSummary'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

    post:
      summary: Create new article (admin only)
      tags:
        - Articles
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleCreate'
      responses:
        '201':
          description: Article created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

  /articles/{slug}:
    get:
      summary: Get article by slug
      tags:
        - Articles
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: Article slug
      responses:
        '200':
          description: Article details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleDetail'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

    put:
      summary: Update article (admin only)
      tags:
        - Articles
      security:
        - bearerAuth: []
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleUpdate'
      responses:
        '200':
          description: Article updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      summary: Delete article (admin only)
      tags:
        - Articles
      security:
        - bearerAuth: []
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Article deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /articles/admin:
    get:
      summary: List all articles including drafts (admin only)
      tags:
        - Articles
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: status
          in: query
          schema:
            type: string
            enum: [draft, published]
        - name: category
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/ArticleSummary'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

  /article-categories:
    get:
      summary: List all article categories
      tags:
        - Categories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/ArticleCategory'
        '500':
          $ref: '#/components/responses/ServerError'

    post:
      summary: Create new article category (admin only)
      tags:
        - Categories
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleCategoryCreate'
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleCategory'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

  /article-categories/{slug}:
    get:
      summary: Get category by slug
      tags:
        - Categories
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleCategory'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ArticleSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        slug:
          type: string
        excerpt:
          type: string
        featured_image_url:
          type: string
          format: uri
          nullable: true
        featured_image_alt_text:
          type: string
          maxLength: 200
          nullable: true
        category:
          $ref: '#/components/schemas/CategorySummary'
        author:
          type: object
          properties:
            id:
              type: string
              format: uuid
            first_name:
              type: string
            email:
              type: string
        published_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
      required:
        - id
        - title
        - slug
        - category
        - author
        - created_at

    ArticleDetail:
      allOf:
        - $ref: '#/components/schemas/ArticleSummary'
        - type: object
          properties:
            content:
              type: string
              description: Sanitized HTML content
            meta_title:
              type: string
              nullable: true
            meta_description:
              type: string
              nullable: true
            status:
              type: string
              enum: [draft, published]
            updated_at:
              type: string
              format: date-time
          required:
            - content
            - status
            - updated_at

    ArticleCreate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        content:
          type: string
          minLength: 1
          description: HTML content (will be sanitized)
        excerpt:
          type: string
          maxLength: 500
          nullable: true
        featured_image_url:
          type: string
          format: uri
          nullable: true
        featured_image_alt_text:
          type: string
          maxLength: 200
          nullable: true
        category_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [draft, published]
          default: draft
        meta_title:
          type: string
          maxLength: 60
          nullable: true
        meta_description:
          type: string
          maxLength: 160
          nullable: true
      required:
        - title
        - content
        - category_id

    ArticleUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        content:
          type: string
          minLength: 1
        excerpt:
          type: string
          maxLength: 500
          nullable: true
        featured_image_url:
          type: string
          format: uri
          nullable: true
        featured_image_alt_text:
          type: string
          maxLength: 200
          nullable: true
        category_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [draft, published]
        meta_title:
          type: string
          maxLength: 60
          nullable: true
        meta_description:
          type: string
          maxLength: 160
          nullable: true
      required:
        - title
        - content
        - category_id

    ArticleCategory:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        description:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - slug
        - created_at

    ArticleCategoryCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          nullable: true
      required:
        - name

    CategorySummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
      required:
        - id
        - name
        - slug

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: object

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                default: Authentication required

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                default: Insufficient permissions

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                default: Resource not found

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                default: Internal server error

